name: Create PR to Dev on Stage PR Merge

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stage
jobs:
  create-pr-to-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create and Auto-Merge PR to Dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create PR using GitHub CLI
          PR=$(gh pr create \
          --base dev \
          --head ${{ github.event.pull_request.head.ref }} \
          --title "Sync changes to dev" \
          --body "This is pr to sync changes from stage to dev")

          echo PR
